// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB86r1Cv0SIWWpDiFUd9W8S4mbKDwpJmfc',
    appId: '1:296473709632:web:bb90fd3380031c778da3a5',
    messagingSenderId: '296473709632',
    projectId: 'treasure-hunt-7d775',
    authDomain: 'treasure-hunt-7d775.firebaseapp.com',
    storageBucket: 'treasure-hunt-7d775.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQpV54fPiDUrR8xAYdkov-cLPCeyb_Pm4',
    appId: '1:296473709632:android:36bc4a19857df1618da3a5',
    messagingSenderId: '296473709632',
    projectId: 'treasure-hunt-7d775',
    storageBucket: 'treasure-hunt-7d775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VW__Vsz4zwkrRrPRn8sp-d60HQ4eDZo',
    appId: '1:296473709632:ios:f1aa1828c7dd340b8da3a5',
    messagingSenderId: '296473709632',
    projectId: 'treasure-hunt-7d775',
    storageBucket: 'treasure-hunt-7d775.appspot.com',
    iosClientId: '296473709632-0nfhnbtpva5an74ikrnq3ot2t8lsnanc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitpodFlutterQuickstart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5VW__Vsz4zwkrRrPRn8sp-d60HQ4eDZo',
    appId: '1:296473709632:ios:f1aa1828c7dd340b8da3a5',
    messagingSenderId: '296473709632',
    projectId: 'treasure-hunt-7d775',
    storageBucket: 'treasure-hunt-7d775.appspot.com',
    iosClientId: '296473709632-0nfhnbtpva5an74ikrnq3ot2t8lsnanc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitpodFlutterQuickstart',
  );
}
